### ISSUE TITLE
print_xml not defined

### ISSUE THREAD

**Issue by BadChoice** [terryyin/lizard#227]
I'm pretty sure it is me, but I can't find any comment about this

when trying to run lizard, I get this error:

```
lizard 
Traceback (most recent call last):
  File "/Volumes/Dades/badchoice/Downloads/lizard-master/lizard.py", line 990, in <module>
    main()
  File "/Volumes/Dades/badchoice/Downloads/lizard-master/lizard.py", line 969, in main
    options = parse_args(argv or sys.argv)
  File "/Volumes/Dades/badchoice/Downloads/lizard-master/lizard.py", line 913, in parse_args
    parser = extend_parser(arg_parser(argv[0]))
  File "/Volumes/Dades/badchoice/Downloads/lizard-master/lizard.py", line 186, in arg_parser
    const=print_xml,
NameError: global name 'print_xml' is not defined
```

I tried both master, and the 1.14.4 release
Using osx High Sierra

**Comment by terryyin** [comment]
Hi Jordi,

Thanks for the notice. It should be fixed now.

**Comment by BadChoice** [comment]
Great! it's working now!
Thank you so much!
