### ISSUE TITLE
Bug: Printer interface failure for warnings

### ISSUE THREAD

**Issue by rakhimov** [terryyin/lizard#234]
```
lizard -w -L 60 -a 5 scripts/*.py
Traceback (most recent call last):
  File "/home/travis/build/rakhimov/scram/pyenv/bin/lizard", line 11, in <module>
    sys.exit(main())
  File "/home/travis/build/rakhimov/scram/pyenv/lib/python3.4/site-packages/lizard.py", line 986, in main
    warning_count = printer(result, options, schema, AllResult)
TypeError: print_clang_style_warning() takes 3 positional arguments but 4 were given
```

**Comment by terryyin** [comment]
Oops, sorry! Fixed.
