### ISSUE TITLE
template.html is not found in package

### ISSUE THREAD

**Issue by TTRh** [terryyin/lizard#271]
Looks like there is something wrong with the setup.py config about template.html it's not in the package at the end:

```
> pip install --user lizard
> lizard --version
1.16.3
> lizard --html my_package/

Traceback (most recent call last):
  File "/home/phoussin/.local/bin/lizard", line 10, in <module>
    sys.exit(main())
  File "/home/phoussin/.local/lib/python3.7/site-packages/lizard.py", line 986, in main
    warning_count = printer(result, options, schema, AllResult)
  File "/home/phoussin/.local/lib/python3.7/site-packages/lizard_ext/htmloutput.py", line 40, in html_output
    output = env.get_template('template.html').render(
  File "/home/phoussin/.local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/phoussin/.local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/phoussin/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/phoussin/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: template.html
```

**Comment by terryyin** [comment]
Sorry for the super late reply. This is now fixed as I've moved the template to an internal string.
