### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by abdallah-eltamaly** [terryyin/lizard#282]
Hello,

I am trying to run hub on a file of size 193 MB and I am getting a memory error like that. Knowing that smaller sizes are working fine.

Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\lizard.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\lizard.py", line 1035, in main
    warning_count = printer(result, options, schema, AllResult)
  File "c:\python34\lib\site-packages\lizard.py", line 822, in print_result
    result = print_and_save_modules(result, scheme)
  File "c:\python34\lib\site-packages\lizard.py", line 789, in print_and_save_modules
    for module_info in all_fileinfos:
  File "c:\python34\lib\site-packages\lizard.py", line 898, in _validate_file
    _not_duplicate(pathname)))
  File "c:\python34\lib\site-packages\lizard.py", line 901, in _not_duplicate
    fhash = md5_hash_file(full_path_name)
  File "c:\python34\lib\site-packages\lizard.py", line 870, in md5_hash_file
    code_md5 = hashlib.md5(source_file.read().encode('utf-8'))
MemoryError

**Comment by terryyin** [comment]
@abdallah-eltamaly is it possible to share this file?
