### ISSUE TITLE
Export xml

### ISSUE THREAD

**Issue by renanalan** [terryyin/lizard#288]
When running lizard without parameters, everything works fine.
When using **lizard -X > output.xml** option, it says:
Traceback (most recent call last):
  File "/usr/local/bin/lizard", line 9, in <module>
    load_entry_point('lizard==1.17.3', 'console_scripts', 'lizard')()
  File "build/bdist.macosx-10.14-intel/egg/lizard.py", line 1035, in main
  File "build/bdist.macosx-10.14-intel/egg/lizard_ext/__init__.py", line 12, in print_xml
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03b8' in position 836206: ordinal not in range(128)

**Comment by anhkhoi** [comment]
the same issue for me

**Comment by forster32** [comment]
the similar issue for me in python2, the reason is that there are Chinese comments in the code.
But after I re-installed with python3, it was fixed

**Comment by terryyin** [comment]
We've completely abandoned python 2 now.
