### ISSUE TITLE
Lizard not working in Python 3.10.12

### ISSUE THREAD

**Issue by ranjithmkumar1992** [terryyin/lizard#400]
I have installed lizard using pip couple of years back and it used to work fine. Recently, when I tried installing on WSL, I see the following error.

```
Traceback (most recent call last):
  File "/home/wslubuntu/.local/bin/lizard", line 8, in <module>
    sys.exit(main())
  File "/home/wslubuntu/.local/lib/python3.10/site-packages/lizard.py", line 1052, in main
    warning_count = printer(result, options, schema, AllResult)
  File "/home/wslubuntu/.local/lib/python3.10/site-packages/lizard.py", line 839, in print_result
    result = print_and_save_modules(result, scheme)
  File "/home/wslubuntu/.local/lib/python3.10/site-packages/lizard.py", line 806, in print_and_save_modules
    for module_info in all_fileinfos:
  File "/home/wslubuntu/.local/lib/python3.10/site-packages/lizard.py", line 551, in __call__
    return self.analyze_source_code(
  File "/home/wslubuntu/.local/lib/python3.10/site-packages/lizard.py", line 568, in analyze_source_code
    tokens = reader.generate_tokens(code)
  File "/home/wslubuntu/.local/lib/python3.10/site-packages/lizard_languages/python.py", line 41, in generate_tokens
    return ScriptLanguageMixIn.generate_common_tokens(
  File "/home/wslubuntu/.local/lib/python3.10/site-packages/lizard_languages/script_language.py", line 18, in generate_common_tokens
    return CodeReader.generate_tokens(
  File "/home/wslubuntu/.local/lib/python3.10/site-packages/lizard_languages/code_reader.py", line 117, in generate_tokens
    def _generate_tokens(source, add, flags=re.NOFLAG):
AttributeError: module 're' has no attribute 'NOFLAG'
```

**Comment by terryyin** [comment]
Thanks. Fixed with https://github.com/terryyin/lizard/commit/ef8ac19ce83d5c7f7e620f7525b6844ef8d4323a.

**Comment by ranjithmkumar1992** [comment]
Thank you for the fix 👍
