### ISSUE TITLE
Version 1.9.7 runtime error

### ISSUE THREAD

**Issue by rickmak** [terryyin/lizard#77]
I got the following error at 1.9.7, run at travis-ci.

```
Traceback (most recent call last):
  File "/usr/local/bin/lizard", line 6, in <module>
    lizard_main(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/lizard.py", line 997, in lizard_main
    printer(result, options, OutputScheme(options.extensions))
TypeError: print_clang_style_warning() takes exactly 2 arguments (3 given)
```

Downgrade to 1.9.6 remove the problem.

**Comment by terryyin** [comment]
Oops, sorry! I’ve fixed the problem and made a new release.

**Comment by rickmak** [comment]
Thanks, it is working now.
