### ISSUE TITLE
Error when running with -X option

### ISSUE THREAD

**Issue by gretzki** [terryyin/lizard#78]
Hi!

Im using latest commit (2c766cad16263ee84f3453f60cf13037b202dba1) with python 2.7.
When running lizard without parameters, everything works fine.
When using -X option, it says
```
 $ lizard -X
Traceback (most recent call last):
  File "/usr/local/bin/lizard", line 5, in <module>
    pkg_resources.run_script('lizard==1.9.6', 'lizard')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1357, in run_script
    exec_(script_code, namespace, namespace)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 47, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/lizard-1.9.6-py2.7.egg/EGG-INFO/scripts/lizard", line 6, in <module>
    
  File "build/bdist.macosx-10.10-intel/egg/lizard.py", line 997, in lizard_main
TypeError: print_xml() takes exactly 2 arguments (3 given)
```

Thanks! :)
Cheers,
Chris

**Comment by fredfoc** [comment]
same here :-(

**Comment by terryyin** [comment]
Sorry! I’ve been travelling. Will look at it asap.

**Comment by terryyin** [comment]
Fixed. And created a new release.

**Comment by fredfoc** [comment]
printer(result, options, OutputScheme(options.extensions)) change to printer(result, options) does the trick..

**Comment by fredfoc** [comment]
oops did not see your message

**Comment by fredfoc** [comment]
thanks for your quick reaction :-)

**Comment by terryyin** [comment]
Thanks for reporting! Let me know if anything is missing.
